name: mapbox_gl_dart
version: 0.3.0
description: Mapbox-gl wrapper for Dart. Library to use Mapbox GL JS in your web Dart projects.
homepage: https://github.com/andrea689/mapbox-gl-dart/
environment:
  sdk: ">=3.3.0  <4.0.0"

dev_dependencies:
  build_runner: ">=2.0.0 <3.0.0"
  build_web_compilers: ">=4.0.0 <5.0.0"
dependencies:
  http: ^1.2.1
